version: "3.9"
networks:
  default:
    driver: bridge
volumes:
  database:
  logs:

services:
  api:
    build: 
      context: ./WebApplication/
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "55555:55555"
    environment:
      - ASPNETCORE_URLS=http://+:55555
      - Database__DatabaseUri=http://database:7474
  database:
    image: neo4j
    networks:
      - default
    environment:
      - NEO4J_AUTH=neo4j/s3cr3t
    volumes:
      - logs:/logs
      - database:/data