version: "3.9"
networks:
  default:
    driver: bridge
volumes:
  database:
  logs:

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "8080:80"
  api:
    build: 
      context: ./WebApplication/
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - "55555:55555" # needs to be open because browsers are not really all that smart :D
    environment:
      - ASPNETCORE_URLS=http://+:55555
      - Database__DatabaseUri=http://database:7474
  database:
    image: neo4j
    networks:
      - default
#    ports: # remember to close ports in production, database should only be accessible from inside docker network
#      - "7474:7474"
#      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/s3cr3t
      - NEO4J_dbms_security_procedures_unrestricted=gds.*,apoc.*
      - NEO4J_dbms_security_procedures_allowlist=gds.*,apoc.*
    volumes:
      - logs:/logs
      - database:/data
      - ./ExternalLibraries/neo4j-graph-data-science-1.4.1-standalone.jar:/plugins/neo4j-graph-data-science-1.4.1-standalone.jar